/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface YoutubeCacheAnalytics {
  api_calls_saved: Generated<number | null>;
  average_response_time_ms: Generated<number | null>;
  cache_hits: Generated<number | null>;
  cache_misses: Generated<number | null>;
  date: Generated<Timestamp>;
  endpoint: string;
  id: Generated<number>;
  quota_saved: Generated<number | null>;
  total_requests: Generated<number | null>;
}

export interface YoutubeContentPopularity {
  last_played: Timestamp | null;
  optimal_ttl_hours: Generated<number | null>;
  play_count: Generated<number | null>;
  popularity_score: Generated<Numeric | null>;
  search_count: Generated<number | null>;
  trending_factor: Generated<Numeric | null>;
  video_id: string;
}

export interface YoutubeQuotaEvents {
  endpoint: string | null;
  event_type: string;
  fallback_type: string | null;
  id: Generated<number>;
  message: string;
  quota_limit: number;
  quota_used: number;
  timestamp: Generated<Timestamp>;
}

export interface YoutubeQuotaTracking {
  date: Generated<Timestamp>;
  id: Generated<number>;
  last_updated: Generated<Timestamp>;
  quota_limit: Generated<number>;
  quota_used: Generated<number>;
  reset_time: Timestamp;
}

export interface YoutubeVideoCache {
  access_count: Generated<number | null>;
  cached_at: Generated<Timestamp>;
  channel_title: string;
  description: string | null;
  duration: string;
  expires_at: Timestamp;
  last_accessed: Generated<Timestamp>;
  like_count: Generated<Int8 | null>;
  published_at: Timestamp;
  source: string;
  tags: Generated<Json | null>;
  thumbnails: Json;
  title: string;
  video_id: string;
  view_count: Generated<Int8 | null>;
}

export interface DB {
  youtube_cache_analytics: YoutubeCacheAnalytics;
  youtube_content_popularity: YoutubeContentPopularity;
  youtube_quota_events: YoutubeQuotaEvents;
  youtube_quota_tracking: YoutubeQuotaTracking;
  youtube_video_cache: YoutubeVideoCache;
}
